# Generated by Django 4.0.4 on 2022-06-30 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_article_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-created',)},
        ),
    ]
