# Generated by Django 4.0.4 on 2022-06-10 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='title',
            new_name='melicode',
        ),
    ]
